language: elixir

elixir:
  - 1.6.6

addons:
  postgresql: '10.4'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
